import { useCallback, useEffect, useState } from 'react'
import { api } from '../lib/api'
const PERMISSIONS = [['status','Ver estado'],['console','Consola y logs'],['players','Jugadores'],['config','Configuración'],['files','Ver archivos'],['mods','Subir mods'],['docker','Ver Docker'],['power','Encender, detener y reiniciar']] as const
interface User { id:string; email:string; createdAt:string; permissions:string[]; superadmin:boolean }
export default function UsersPanel(){
 const [users,setUsers]=useState<User[]>([]),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[selected,setSelected]=useState<string[]>(['status']),[error,setError]=useState(''),[message,setMessage]=useState('')
 const load=useCallback(async()=>{try{const d=await api<{users:User[]}>('/api/users');setUsers(d.users);setError('')}catch(e){setError(e instanceof Error?e.message:'Error')}},[])
 useEffect(()=>{load()},[load])
 const toggle=(permission:string)=>setSelected(p=>p.includes(permission)?p.filter(x=>x!==permission):[...p,permission])
 async function create(e:React.FormEvent){e.preventDefault();try{await api('/api/users',{method:'POST',body:{email,password,permissions:selected}});setEmail('');setPassword('');setMessage('Cuenta creada correctamente');load()}catch(err){setError(err instanceof Error?err.message:'Error')}}
 async function toggleUser(user:User,permission:string){const permissions=user.permissions.includes(permission)?user.permissions.filter(p=>p!==permission):[...user.permissions,permission];try{await api(`/api/users/${user.id}`,{method:'PUT',body:{permissions}});load()}catch(e){setError(e instanceof Error?e.message:'Error')}}
 async function remove(user:User){if(!confirm(`¿Eliminar la cuenta ${user.email}?`))return;try{await api(`/api/users/${user.id}`,{method:'DELETE'});load()}catch(e){setError(e instanceof Error?e.message:'Error')}}
 return <div className="grid gap-5 xl:grid-cols-[380px_1fr]"><form onSubmit={create} className="panel h-fit"><h3 className="font-semibold">Crear una cuenta</h3><p className="mt-1 text-xs text-slate-500">Solo el superadmin puede crear usuarios.</p>{error&&<p className="mt-3 text-sm text-red-400">{error}</p>}{message&&<p className="mt-3 text-sm text-emerald-400">{message}</p>}
 <label className="field-label">Correo electrónico</label><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="field" placeholder="usuario@correo.com"/>
 <label className="field-label">Contraseña temporal</label><input required minLength={10} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="field" placeholder="Mínimo 10 caracteres"/>
 <p className="field-label">Permisos iniciales</p><div className="space-y-2">{PERMISSIONS.map(([id,label])=><label key={id} className="flex cursor-pointer items-center justify-between rounded-lg bg-slate-900 p-2.5 text-sm"><span>{label}</span><input type="checkbox" checked={selected.includes(id)} onChange={()=>toggle(id)} className="accent-emerald-500"/></label>)}</div><button className="button-primary mt-5 w-full">Crear cuenta</button></form>
 <section className="panel min-w-0"><h3 className="font-semibold">Cuentas existentes</h3><div className="mt-4 space-y-3">{users.map(user=><div key={user.id} className="rounded-xl border border-slate-800 bg-slate-900/50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-medium">{user.email}</p><p className="text-xs text-slate-500">{user.superadmin?'Superadmin · acceso total':`Creada ${new Date(user.createdAt).toLocaleDateString()}`}</p></div>{!user.superadmin&&<button onClick={()=>remove(user)} className="text-xs text-red-500 hover:text-red-300">Eliminar cuenta</button>}</div>
 {!user.superadmin&&<div className="mt-3 flex flex-wrap gap-2">{PERMISSIONS.map(([id,label])=><button key={id} onClick={()=>toggleUser(user,id)} className={`rounded-full border px-2.5 py-1 text-xs ${user.permissions.includes(id)?'border-emerald-800 bg-emerald-950 text-emerald-400':'border-slate-700 text-slate-500'}`}>{label}</button>)}</div>}</div>)}</div></section></div>
}
